baseURL = 'https://mrwillingham.com/'
languageCode = 'en-us'
title = "Mr. Willingham's Classes"
theme = 'ananke'

[taxonomies]
  tag = "tags"
  unit = "units"
  standard = "standards"
  resource = "resources"

[params]
  custom_css = ["css/lesson-sections.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true